grid_dir : "/shares/feldmann.ics.mnf.uzh/Andrin/IC_GEN/grid/"
tipsy_dir : "/shares/feldmann.ics.mnf.uzh/Andrin/IC_GEN/raw/"
model_dir : "models/"
output_tipsy_file : "particles.tipsy"
model_type : "FNO" # UNet, FNO
input_grid_size : 128
grid_size : 64
learning_rate : 0.002
n_epochs : 20
stride : 20
steps : 5
start : 0
sequential_mode : True
# cosmology parameters
# all values have to agree with the values used in the simulation
redshift_start : 49
redshift_end : 0
box_size : 60 # Mpc/h
dt_PKDGRAV3 : 0.0012517188943844037 # Given redshift 49
num_particles : 16777216 # 256^3
omega_M : 0.32
omega_L : 0.68