data_dir : "/shares/feldmann.ics.mnf.uzh/Andrin/IC_GEN/grid/"
model_dir : "models/"
output_tipsy_file : "particles.tipsy"
input_grid_size : 128
grid_size : 64
learning_rate : 0.004
n_epochs : 30
stride : 90
# cosmology parameters
# all values have to agree with the values used in the simulation
redshift_start : 49
redshift_end : 0
box_size : 60 # Mpc/h
dt_PKDGRAV3 : 0.0012517188943844037 # Given redshift 49
num_particles : 16777216 # 256^3
omega_M : 0.32
omega_L : 0.68