train_data_dir : "/shares/feldmann.ics.mnf.uzh/Andrin/IC_GEN/grid/"
test_data_dir : "/shares/feldmann.ics.mnf.uzh/Andrin/IC_GEN/grid/"
model_params_file : "/model_params/fno.eqx"
input_grid_size : 128
grid_size : 64
learning_rate : 0.004
n_epochs : 100
stride : 50