# Dataset
# grid_dir : "/shares/feldmann.ics.mnf.uzh/Andrin/IC_GEN/grid/" #"/shares/feldmann.ics.mnf.uzh/Andrin/firefly/"
grid_dir : "/shares/feldmann.ics.mnf.uzh/Andrin/IC_GEN/grid/"
input_grid_size : 128
grid_size : 128
file_index_stride :
- 2
- 3
- 5
- 10
- 30
- 50
file_index_steps : 6
file_index_start : 0
total_index_steps : 100
flip : True 
normalizing_function : "ssm" # log_growth, delta, ssm

# Training parameters
learning_rate : 0.002
include_potential : False
sequential_skip_channels : 0
stepwise_epochs : 20
mixed_epochs : 0
sequential_epochs : 0
unique_networks : False
model_dir : "/data/arehma/models/layers2/"
model_type : "FNO" # UNet, FNO
activation : "tanh" # relu, tanh

# FNO parameters
fno_modes : 32
fno_input_channels : 1 # sequential_skip_channels + include_potential * 1 + 1
fno_hidden_channels : 16
fno_output_channels : 1 # sequential_skip_channels + 1
fno_n_layers : 5
fno_increasing_modes : True

# UNet parameters
unet_input_channels : 1
unet_hidden_channels : 24
unet_output_channels : 1
unet_num_levels : 2

# cosmology parameters
box_size : 60 # Mpc/h
num_particles : 16777216 # 256^3
omega_M : 0.32
omega_L : 0.68