# dataset
grid_dir : "/shares/feldmann.ics.mnf.uzh/Andrin/IC_GEN/grid/" #"/shares/feldmann.ics.mnf.uzh/Andrin/firefly/"
input_grid_size : 128
grid_size : 64
file_index_stride : 
- 1
file_index_steps : 1
file_index_start : 0
total_index_steps : 100
flip : True 
normalizing_function : "log_growth" # log_growth, delta, none

# Training parameters
learning_rate : 0.002
include_potential : False
sequential_skip_channels : 0
stepwise_epochs : 20
mixed_epochs : 0
sequential_epochs : 0
unique_networks : True
model_dir : "/data/arehma/models/ranges-fd"
model_type : "FNO" # UNet, FNO
activation : "relu" # relu, tanh

# FNO parameters
fno_modes : 32
fno_input_channels : 1
fno_hidden_channels : 16
fno_output_channels : 1
fno_n_layers : 5
fno_increasing_modes : True

# UNet parameters
unet_input_channels : 2
unet_hidden_channels : 8
unet_output_channels : 2
unet_num_levels : 4

# cosmology parameters
box_size : 60 # Mpc/h
num_particles : 16777216 # 256^3
omega_M : 0.32
omega_L : 0.68