# dataset
grid_dir : "/shares/feldmann.ics.mnf.uzh/Andrin/IC_GEN/grid/" #"/shares/feldmann.ics.mnf.uzh/Andrin/firefly/"
input_grid_size : 128
grid_size : 64
file_index_stride : 
- 1
- 2
- 4
- 8
- 16
- 24
- 45
file_index_steps : 7
file_index_start : 0
total_index_steps : 100
flip : True 
normalizing_function : "norm_log_delta_one"

# Training parameters
learning_rate : 0.002
include_potential : True
sequential_skip_channels : 1
stepwise_epochs : 40
mixed_epochs : 30
sequential_epochs : 0
unique_networks : True
model_dir : "models/ranges"
model_type : "FNO" # UNet, FNO
activation : "relu" # relu, tanh

# FNO parameters
fno_modes : 32
fno_input_channels : 2
fno_hidden_channels : 3
fno_output_channels : 2
fno_n_layers : 5
fno_increasing_modes : True

# UNet parameters
unet_input_channels : 2
unet_hidden_channels : 8
unet_output_channels : 2
unet_num_levels : 4

# cosmology parameters
box_size : 60 # Mpc/h
num_particles : 16777216 # 256^3
omega_M : 0.32
omega_L : 0.68